### ISSUE TITLE
parcel plugin not respecting "extends" keyword

### ISSUE THREAD

**Issue by andykais** [cevek/ttypescript#53] opened 2019-06-05 14:39 UTC
I have tsconfig files in a folder `tsconfig/`. I added a toplevel `tsconfig.json` file with the contents
```json
{
  "extends": "./tsconfig/tsconfig.json"
}
```
so my project directory looks like so:
```
src/
tsconfig/
  tsconfig.json
  tsconfig.declarations.json
tsconfig.json
package.json
```
I created this file specifically so this plugin can find my nested configs. Unfortunately it does not seem to notice the tsconfigs in the `tsconfig/` folder. I know it does not because I have tried leaving an invalid json file in tsconfig/tsconfig.json and parcel still builds without issue. On a related note, if I could specify the location of my tsconfig file like I can with `ttsc`, I could avoid these extra steps.

**Comment by cevek** [comment] 2019-06-07 10:31
Yeah, the problem is here
https://github.com/parcel-bundler/parcel/blob/master/packages/core/parcel-bundler/src/assets/TypeScriptAsset.js#L37

parcel just uses `tsconfig.compilerOptions` without try to parse this config by typescript internal tools which should normalize config by reading extends and etc

**Comment by andykais** [comment] 2019-06-07 13:29
ah, good to know. Is there an issue already open in parcel-bundler?

**Comment by cevek** [comment] 2019-06-07 13:37
So, I don't see anything

**Comment by andykais** [comment] 2019-06-07 14:47
actually it looks like a bug has already been reported https://github.com/parcel-bundler/parcel/issues/2856

**Comment by cevek** [comment] 2019-12-01 06:23
Fixed in parcel@2

**Closed by cevek** 2019-12-01 06:23 UTC
