### ISSUE TITLE
Watch mode & transformers

### ISSUE THREAD

**Issue by madou** [cevek/ttypescript#86] opened 2020-04-01 21:15 UTC
Hey mate! I'm running some code with `ttsc --watch` mode enabled and it seems on re-compilation it doesn't apply the transformer? (Or my transformer does something odd and not work with watch mode?)

Is there any knowledge you have around this?

Transformer in question: https://github.com/atlassian-labs/compiled-css-in-js
Code in question: https://github.com/compiled/website

```
git clone git@github.com:compiled/website.git
git checkout dd74001bfb16ebc3ee3e26c11d9ec49f09cbd684
yarn
yarn help-me
```

And then edit something inside `packages/ui/src`

Cheers!

**Comment by Zn4rK** [comment] 2020-04-01 21:23
Wow! I've run in to this problem exactly with a custom transformer I'm working on.

The first time the transformer runs, it works. The second time it gets compiled, it doesn't work. Then I trigger a third build, and the second compilation shows up....

**Comment by nonara** [comment] 2020-04-01 21:56
Would either of you mind seeing if the same happens with https://npmjs.com/ts-patch ? I have noticed some strange activity on tsserverlibrary's watch. I'm wondering if it may be related

**Comment by madou** [comment] 2020-04-01 22:38
Can do - will be a day or two :)

**Comment by Zn4rK** [comment] 2020-04-02 07:53
I've just tested with ts-patch, and I'm seeing the same thing there. 

Just out of curiosity I decided to test the same thing with `webpack`, `ts-loader` and `ttypescript` (and TypeScript with ts-patch), and I'm seeing the same behaviour there. It seems like the program is re-used...

I also tried with the archived `awesome-typescript-loader` and `ttypescript`. And ~8/10 it works as expected - i.e. it re-compiles as it should.

**Comment by cevek** [comment] 2020-04-02 08:26
@Zn4rK Can you share please your transformer so that I can inspect the problem?

**Comment by Zn4rK** [comment] 2020-04-02 08:30
@cevek Can't share the transformer right now. I'll set up a reproduction of the transformer later today though! 👍

**Comment by cevek** [comment] 2020-04-02 08:38
@Zn4rK thank you!

@madou your example works for me, every change I've done in root.tsx transpiles into root.js in dist folder
What am I doing wrong?

**Comment by Zn4rK** [comment] 2020-04-02 18:39
@cevek I've made a reproduction here:
https://github.com/Zn4rK/ttypescript-repro

Edit the argument name in the function in `index.ts` and check the result of `dist/src/other.js`. It should have updated the object with a new property with the value of the argument name of the function.

I'm not able to consistently reproduce this issue, but whilst building the crude reproduction, I've managed to have it happen few times, but I'm leaning more and more into thinking that running `ttsc --watch` still works as expected and the issue is that the file is being accessed to quickly. I.e TypeScript has no time to emit it before I'm opening it. Tailing the file eventually yields the correct result.

***However!***

Using webpack with ts-loader, I'm able to reproduce the error everytime. The first compilation works. The second time it doesn't work, and by the third time I've edited the file, the second compilation shows up. I have no clue on how to start debugging that. Is it `ts-loader`, `webpack` or `ttypescript`? Do we know about anyway around this?

Using the ***archived*** (i.e. not an option anymore) `awesome-typescript-loader` I'm seeing more consistent results...

**Comment by madou** [comment] 2020-04-02 18:47
> @Zn4rK thank you!
> 
> @madou your example works for me, every change I've done in root.tsx transpiles into root.js in dist folder
> What am I doing wrong?

hey thanks for having a look - yeah it's weird it's not happening now. unsure why! it would be quite obvious when it happens though - Parcel would blow up because it can't run the untransformed code

**Comment by cevek** [comment] 2020-04-02 19:41
@Zn4rK the problem of your transformer is that it relies that after any change of any file transformer will process every file in project, but it does only in typescript watch mode, webpack, parcel run transformations in simple mode, which file has changed is processed.

You can console.log your transformations in transformer.ts to debug what files are processed
```ts
console.log(sourceFile.fileName);
const result = createContext(program);
```

**Comment by cevek** [comment] 2020-04-02 19:46
@madou Be careful with parcel and `ttsc -w` running simultaneously, because they both write to dist folder
these two watchers will override result of each other: parcel without transformations, ttsc with transformations

**Comment by madou** [comment] 2020-04-02 21:29
they're writing the different `dist` folders :) but the warning makes sense, thanks.

**Comment by Zn4rK** [comment] 2020-04-05 15:17
First of all, @madou, sorry for hijacking this issue.

> @Zn4rK the problem of your transformer is that it relies that after any change of any file transformer will process every file in project, but it does only in typescript watch mode, webpack, parcel run transformations in simple mode, which file has changed is processed.

I've had some time to work on the original transformer in question. I've also updated the "[reproduction](https://github.com/Zn4rK/ttypescript-repro)" to reflect that. The updated example better reflects how I'm actually using the transformer. The dependency graph is updated, and when "index.ts" is edited, it also transforms "other.ts".

The problem I was describing earlier still exists for me with `ts-loader`. I'm almost certain that this problem is not because of `ttypescript`.

One the first run:
```
sourceFile index.ts result argument
sourceFile other.ts result argument
sourceFile index.ts result argument
sourceFile other.ts result argument
```

After changing something and triggering a rebuild:
```
sourceFile other.ts result argument
sourceFile index.ts result newArgument
sourceFile other.ts result newArgument
sourceFile index.ts result newArgument
```

Triggering a third rebuild without changing the argument gets the expected result.

(Waiting "long enough" also seems to yield the expected result - and the ordering of the files is in the original order)

I'm still debugging, but I think that this is caused by some internal order with ts-loader or webpack.
If anyone has any ideas I'm all ears!

**Comment by madou** [comment] 2020-04-05 21:30
no worries @Zn4rK it's good you're getting somewhere with this 😄

**Comment by cevek** [comment] 2020-09-07 09:44
I close this issue. If you have any unresolved problems I will reopen it.

**Closed by cevek** 2020-09-07 09:44 UTC
